language: scala

jdk:
  - openjdk8
  - openjdk11

script:
  - sbt test

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

notifications:
  email:
  - adriaan.moors@lightbend.com
  - seth.tisue@lightbend.com
